# Generated by Django 3.2.8 on 2021-11-22 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id_attendance', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('service_duration', models.DurationField(db_column='DuracaoServico')),
                ('observation', models.CharField(blank=True, db_column='Observacao', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id_breed', models.BigAutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('name_breed', models.CharField(db_column='Raca', max_length=50, verbose_name='Raça')),
                ('groomable', models.BooleanField(db_column='TosaEstetica', default=False, verbose_name='Tosa Estética')),
                ('last_update', models.DateTimeField(auto_now=True, db_column='LastUpdate')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.breed')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='PetId')),
                ('name_pet', models.CharField(db_column='Nome', default='n', max_length=50)),
                ('puppy', models.BooleanField(db_column='Filhote', default=False, verbose_name='Filhote')),
                ('sex', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('D', 'Desconhecido')], db_column='Sexo', default='D', max_length=1, verbose_name='Sexo')),
                ('last_update', models.DateTimeField(auto_now=True, db_column='LastUpdate')),
                ('breed_id', models.ForeignKey(db_column='RacaId', default=-1, on_delete=django.db.models.deletion.CASCADE, to='tutorials.breed')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.BigAutoField(db_column='Id', default=42, primary_key=True, serialize=False)),
                ('name_tutor', models.CharField(max_length=50)),
                ('cellphone1', models.CharField(db_column='Telefone1', default='-1', max_length=15, verbose_name='Telefone Principal')),
                ('cellphone2', models.CharField(blank=True, db_column='Telefone2', max_length=15, null=True, verbose_name='Outro Telefone')),
                ('endereco_tutor', models.CharField(blank=True, max_length=300)),
                ('last_update', models.DateTimeField(auto_now=True, db_column='LastUpdate')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id_order', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(auto_now_add=True, db_column='CreationTime')),
                ('last_update', models.DateTimeField(auto_now=True, db_column='LastUpdate')),
                ('pet_ids', models.ManyToManyField(through='tutorials.Attendance', to='tutorials.Pet')),
                ('tutor_id', models.ForeignKey(db_column='TutorId', on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name_service', models.CharField(db_column='NomeServico', max_length=80, verbose_name='Nome Serviço')),
                ('time_service', models.DurationField(blank=True, db_column='TempoMedioGrupoRaca', null=True)),
                ('short_fur', models.DurationField(blank=True, db_column='TempoMedioPeloCurto', null=True)),
                ('medium_fur', models.DurationField(blank=True, db_column='TempoMedioPeloMedio', null=True)),
                ('long_fur', models.DurationField(blank=True, db_column='TempoMedioPeloLongo', null=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_column='LastUpdate')),
                ('set', models.ManyToManyField(through='tutorials.Group', to='tutorials.Breed')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='id_tutor',
            field=models.ForeignKey(db_column='TutorId', default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='pets_set', to='tutorials.tutor'),
        ),
        migrations.AddField(
            model_name='group',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.service'),
        ),
        migrations.AddField(
            model_name='breed',
            name='set',
            field=models.ManyToManyField(through='tutorials.Group', to='tutorials.Service'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='id_order',
            field=models.ForeignKey(db_column='ServiceOrderFK', on_delete=django.db.models.deletion.CASCADE, related_name='attendances_set', to='tutorials.serviceorder'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.pet'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.service'),
        ),
    ]
