# Generated by Django 3.2.8 on 2021-10-31 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False, verbose_name='PetId')),
                ('name_pet', models.CharField(default='n', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(default='n', primary_key=True, serialize=False, verbose_name='ServiceId')),
                ('name_service', models.CharField(default='0:30:00', max_length=70)),
                ('small_time', models.DurationField(default='0:30:00')),
                ('medium_time', models.DurationField(default='0:35:00')),
                ('large_time', models.DurationField(default='0:40:00')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('cellphone_tutor', models.IntegerField(primary_key=True, serialize=False)),
                ('name_tutor', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AddField(
            model_name='pet',
            name='tutor_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutor'),
        ),
    ]
