# Generated by Django 3.2.8 on 2021-10-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(default='0:30:00', max_length=70)),
                ('small_time', models.TimeField(default='0:30:00')),
                ('medium_time', models.TimeField(default='0:35:00')),
                ('large_time', models.TimeField(default='0:40:00')),
            ],
        ),
    ]
